### ISSUE TITLE
Release 0.5 introduced major slowdown on Julia 0.3

### ISSUE THREAD

**Issue by garborg** [JuliaLang/SortingAlgorithms.jl#11]
```julia
using DataFrames
df = DataFrame()
n = 700_000
df[:ID] = [string("ID",rand(1000:9999)) for a in 1:n]
df[:YEAR] = [rand(1980:2015) for a in 1:n]
@time sort(df,cols=:ID)
 ```

slowed from 3.5 seconds to 212.5 seconds on `release-0.3` (fine on `master`) with GC time climbing from 6% to 98%. Similar slowdown reported in original issue JuliaStats/DataFrames.jl#798.

**Comment by disleyland** [comment]
this is part of the ongoing type instability problem at the moment.  

@time sort(df,cols=:ID) takes ages, but
@time  sort(df[:ID].data) gets us back to 3 seconds.  enforcing type stability in the dataframe will further reduce time down to .7 seconds!

**Comment by disleyland** [comment]
As Julia 0.4 (as of 4.3 at least) has solved this issue, should this be closed?

**Comment by kmsquire** [comment]
Certainly the original code posted above seems fine now (on Julia v0.4 and v0.5).

(@garborg, assuming this wasn't `DataFrames`-specific, this issue probably should have been posted in `julialang`, since the main sorting algorithms are defined there.  This package just has implementations of alternative algorithms.)

**Comment by garborg** [comment]
Thanks, @kmsquire. I thought profiling the example pointed here, but you know the sorting code much better than I do -- I bet I misread something.

**Comment by kmsquire** [comment]
It's also possible that `DataFrames` uses `TimSort`, which is defined here. So it might have actually been the right place (though the fix was in Julia itself).
