### ISSUE TITLE
Test error on latest julia release-0.4

### ISSUE THREAD

**Issue by garrison** [JuliaLang/SortingAlgorithms.jl#15]
Here is the test error:

```
ERROR: LoadError: argument is an abstract type; size is indeterminate
 in randnans at /home/garrison/.julia/v0.4/SortingAlgorithms/test/runtests.jl:44
 [inlined code] from /home/garrison/.julia/v0.4/SortingAlgorithms/test/runtests.jl:98
```

The code in question (`reinterpret(Float64,[rand(Uint64)|0x7ff8000000000000 for i=1:100])`) works on julia-0.4.0-rc1 but fails on more recent `release-0.4` commits (e.g. JuliaLang/julia@1af871b).

**Comment by garrison** [comment]
Oddly enough, changing `Uint64` to `@compat(UInt64)` fixes the issue.  I'll make a PR that fixes this (and other things for 0.4 compatibility here), but I think this failure is a regression in julia itself.

**Comment by yuyichao** [comment]
This is a known problem with the deprecated binding not being constant. It should be fixed on master and the 0.4 branch now, although the deprecation warning is good to be fixed anyway.

Note that you don't need `@compat` for `UInt*`

**Comment by garrison** [comment]
FYI, I was using the latest commit from `release-0.4`; it does not seem to be fixed there yet.

**Comment by yuyichao** [comment]
OK. I thought Tony has already merged the second/third round before testing the next one but probably not .... https://github.com/JuliaLang/julia/pull/13182

**Comment by yuyichao** [comment]
https://github.com/JuliaLang/julia/commit/2b69ef6662aadda2dd26f2e37168fa4f05559153
