### ISSUE TITLE
mapping from unsorted to sorted result

### ISSUE THREAD

**Issue by achen12** [JuliaLang/SortingAlgorithms.jl#18]
Not a breaking issue, but just a question.

What would be a good way for me to get the mapping from the unsorted input to the sorted output?
I looked at the source code, and there doesn't seem to be an option for that.
Is there a reason why outputting the mapping would be bad in general or in Julia?

**Comment by simonster** [comment]
You can use `sortperm` for this. This is implemented in Base, but you can use algorithms from this package with it, e.g. `sortperm(x, alg=TimSort)`.
